// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:66cc5b86-18f2-4dba-905a-12a4301e7fc9',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'chickenfreshouttheki-hosting-mobilehub-938827609',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1sp38jl71cebo.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '33b02d3b1003422688a2d5fc8e0cdcbf',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '201973bc-e23b-4d2d-a682-0e210aca48a9',
    'aws_project_name': 'ChickenFreshOutTheKitchen_Admin',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'chickenfreshouttheki-mobilehub-938827609',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_SD0E0EHXK',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '3m82480j975mdpioc8fsl1o86i',
}

export default awsmobile;
